<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cargo_behavior_swarm_flocking</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="christopherrichard2525@gmail.com">gadzz</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_cmake</depend>
  <depend>ament_cmake_ros</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>cargo_core</depend>
  <depend>cargo_msgs</depend>
  <depend>cargo_behavior</depend>
  <depend>geometry_msgs</depend>
  <depend>cargo_motion_reference_handlers</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>trajectory_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>eigen</depend>
  <depend>rclcpp_components</depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
